### ISSUE TITLE
Do writes to backing store asynchronously

### ISSUE THREAD

**Issue by masih** [ipni/dhstore#5]
Consider doing this in a separate goroutine so that the API can return right away without having to wait for the data to be processed, and possibly having the client time out. There may be a large batch to process.

_Originally posted by @gammazero in https://github.com/ipni/dhstore/pull/4#discussion_r1069589517_

**Comment by gammazero** [comment]
After reexamination, this issue can be closed. The backing store should take care of making the write asynchronous if applicable. However, the dhstore code should wait for the write call to return so that success or failure can be determined, which will affect whether the operation is considered a success or failure. This will determine if the advertisement processing stops or continues.
